const Data = [
  {
    id: 1,
    heading: "nicht lieferbar",
    img: "Img.svg",
    name: "Canify",
    btn1: "THC 18% ",
    btn2: "CBD <1%",
    desciption: "Cannabis Flos 18/1 PT Mango",
    text1: "Kultivar",
    text2: "Mango",
    text3: "Genetik",
    text4: "Hybrid",
    sign: "€",
    number: "11,66",
    number2: "1",
    text5: "pro Gramm",
    button: "in den Warenkorb",
    img2: "Bestrahlt.svg",
  },
  {
    id: 2,
    heading: "nicht lieferbar",
    img: "Img.svg",
    name: "Canify",
    btn1: "THC 18% ",
    btn2: "CBD <1%",
    desciption: "Cannabis Flos 18/1 PT Mango",
    text1: "Kultivar",
    text2: "Mango",
    text3: "Genetik",
    text4: "Hybrid",
    sign: "€",
    number: "11,66",
    number2: "1",
    text5: "pro Gramm",
    button: "in den Warenkorb",
    img2: "Bestrahlt.svg",
  },
  {
    id: 3,
    heading: "nicht lieferbar",
    img: "Img.svg",
    name: "Canify",
    btn1: "THC 18% ",
    btn2: "CBD <1%",
    desciption: "Cannabis Flos 18/1 PT Mango",
    text1: "Kultivar",
    text2: "Mango",
    text3: "Genetik",
    text4: "Hybrid",
    sign: "€",
    number: "11,66",
    number2: "1",
    text5: "pro Gramm",
    button: "in den Warenkorb",
    img2: "Bestrahlt.svg",
  },
];
export default Data;
