const Data2 = [
  {
    id: 1,
    heading: "sofort lieferbar",
    heading2: "Neu",
    img: "Img.svg",
    name: "Canify",
    btn1: "THC 25%  ",
    btn2: "CBD <1%",
    desciption: "Cannabis Flos 22/1 PT Ku.Pink Kush DAB Canify",
    text1: "Kultivar",
    text2: "Pink Kush",
    text3: "Genetik",
    text4: "Hybrid",
    sign: "€",
    number: "11,66",
    number2: "1",
    text5: "pro Gramm",
    button: "in den Warenkorb",
    img2: "Bestrahlt.svg",
  },
  {
    id: 2,
    heading: "sofort lieferbar",
    heading2: "Neu",
    img: "Img.svg",
    name: "Canify",
    btn1: "THC 25%  ",
    btn2: "CBD <1%",
    desciption: "Cannabis Flos 22/1 PT Ku.Pink Kush DAB Canify",
    text1: "Kultivar",
    text2: "Pink Kush",
    text3: "Genetik",
    text4: "Hybrid",
    sign: "€",
    number: "11,66",
    number2: "1",
    text5: "pro Gramm",
    button: "in den Warenkorb",
    img2: "Bestrahlt.svg",
  },
  {
    id: 3,
    heading: "sofort lieferbar",
    heading2: "Neu",
    img: "Img.svg",
    name: "Canify",
    btn1: "THC 25%  ",
    btn2: "CBD <1%",
    desciption: "Cannabis Flos 22/1 PT Ku.Pink Kush DAB Canify",
    text1: "Kultivar",
    text2: "Pink Kush",
    text3: "Genetik",
    text4: "Hybrid",
    sign: "€",
    number: "11,66",
    number2: "1",
    text5: "pro Gramm",
    button: "in den Warenkorb",
    img2: "Bestrahlt.svg",
  },
];
export default Data2;
